#ifndef __OCARINA_GENERATED_ACTIVITY_H_
#define __OCARINA_GENERATED_ACTIVITY_H_ 
#include <request.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void display_parking_address_deliver 
    (__po_hi_request_t* request);

void* display_parking_address_job (void);

void entry_image_processing_thread_deliver 
    (__po_hi_request_t* request);

void* entry_image_processing_thread_job (void);

void exit_image_processing_thread_deliver 
    (__po_hi_request_t* request);

void* exit_image_processing_thread_job (void);

void car_passed_gate_handler_thread_deliver 
    (__po_hi_request_t* request);

void* car_passed_gate_handler_thread_job (void);

void calculate_price_deliver 
    (__po_hi_request_t* request);

void* calculate_price_job (void);

void car_passed_exit_thread_deliver 
    (__po_hi_request_t* request);

void* car_passed_exit_thread_job (void);

void check_slots_thread_deliver 
    (__po_hi_request_t* request);

void* check_slots_thread_job (void);

void start_exit_camera_deliver 
    (__po_hi_request_t* request);

void* start_exit_camera_job (void);

void start_entry_camera_deliver 
    (__po_hi_request_t* request);

void* start_entry_camera_job (void);

void should_open_exit_gate_deliver 
    (__po_hi_request_t* request);

void* should_open_exit_gate_job (void);

void display_wallet_deliver 
    (__po_hi_request_t* request);

void* display_wallet_job (void);

void __po_hi_main_deliver 
    (__po_hi_request_t* request);

#endif
