#include <po_hi_gqueue.h>
#include <deployment.h>
#include <po_hi_types.h>
#include <request.h>
#include <po_hi_task.h>
#include <types.h>
#include "subprograms.h"
#include <activity.h>
#include <po_hi_main.h>
#include <po_hi_transport.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
__po_hi_port_t __po_hi_display_parking_address_data_output_local_destinations[1] = {parking_display_global_display_parking_address};
__po_hi_uint8_t __po_hi_display_parking_address_woffsets[__po_hi_display_parking_address_nb_ports];
__po_hi_uint8_t __po_hi_display_parking_address_offsets[__po_hi_display_parking_address_nb_ports];
__po_hi_uint8_t __po_hi_display_parking_address_used_size[__po_hi_display_parking_address_nb_ports];
__po_hi_uint8_t __po_hi_display_parking_address_empties[__po_hi_display_parking_address_nb_ports];
__po_hi_uint8_t __po_hi_display_parking_address_first[__po_hi_display_parking_address_nb_ports];
__po_hi_request_t __po_hi_display_parking_address_recent[__po_hi_display_parking_address_nb_ports];
__po_hi_port_t __po_hi_display_parking_address_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_display_parking_address_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_display_parking_address_history[0];
__po_hi_uint8_t __po_hi_display_parking_address_n_dest[__po_hi_display_parking_address_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_display_parking_address_fifo_size[__po_hi_display_parking_address_nb_ports] = {__PO_HI_GQUEUE_FIFO_INDATA,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_display_parking_address_destinations[__po_hi_display_parking_address_nb_ports] = {NULL,__po_hi_display_parking_address_data_output_local_destinations};

/*!
 * \fn void display_parking_address_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task display_parking_address
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (display_parking_address_deliver) stores the incoming request for the 
 * taskdisplay_parking_address
 */
void display_parking_address_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case display_parking_address_global_data_input:
    {
      __po_hi_gqueue_store_in (main_display_parking_address_k, display_parking_address_local_data_input, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* display_parking_address_job (void)
 * \brief Function executed by the task display_parking_address
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Get the IN ports values*/
void* display_parking_address_job (void)
{
  __po_hi_local_port_t port;
  __po_hi_request_t static data_input_request;
  parking_system__alpha_type parking_address_request_var;
  __po_hi_request_t data_output_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (main_display_parking_address_k, __po_hi_display_parking_address_nb_ports, __po_hi_display_parking_address_queue, __po_hi_display_parking_address_fifo_size, __po_hi_display_parking_address_first, __po_hi_display_parking_address_offsets, __po_hi_display_parking_address_woffsets, __po_hi_display_parking_address_n_dest, __po_hi_display_parking_address_destinations, __po_hi_display_parking_address_used_size, __po_hi_display_parking_address_history, __po_hi_display_parking_address_recent, __po_hi_display_parking_address_empties, __po_hi_display_parking_address_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (main_display_parking_address_k, &(port));
    __po_hi_compute_next_period (main_display_parking_address_k);
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (main_display_parking_address_k, display_parking_address_local_data_input))
    {
          __po_hi_gqueue_get_value (main_display_parking_address_k, display_parking_address_local_data_input, &(data_input_request));
      __po_hi_gqueue_next_value (main_display_parking_address_k, display_parking_address_local_data_input);

    }
    /*  Call implementation*/
    parking_system__display_parking_address (data_input_request.vars.display_parking_address_global_data_input.display_parking_address_global_data_input, &(parking_address_request_var));
    /*  Set the OUT port values*/
    data_output_request.vars.display_parking_address_global_data_output.display_parking_address_global_data_output = data_output_request_var;
    data_output_request.port = display_parking_address_global_data_output;
    __po_hi_gqueue_store_out (main_display_parking_address_k, display_parking_address_local_data_output, &(data_output_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (main_display_parking_address_k, display_parking_address_global_data_output);
  }
}

__po_hi_port_t __po_hi_entry_image_processing_thread_plate_number_local_destinations[1] = {network_module_global_tables_wallet_check};
__po_hi_uint8_t __po_hi_entry_image_processing_thread_woffsets[__po_hi_entry_image_processing_thread_nb_ports];
__po_hi_uint8_t __po_hi_entry_image_processing_thread_offsets[__po_hi_entry_image_processing_thread_nb_ports];
__po_hi_uint8_t __po_hi_entry_image_processing_thread_used_size[__po_hi_entry_image_processing_thread_nb_ports];
__po_hi_uint8_t __po_hi_entry_image_processing_thread_empties[__po_hi_entry_image_processing_thread_nb_ports];
__po_hi_uint8_t __po_hi_entry_image_processing_thread_first[__po_hi_entry_image_processing_thread_nb_ports];
__po_hi_request_t __po_hi_entry_image_processing_thread_recent[__po_hi_entry_image_processing_thread_nb_ports];
__po_hi_port_t __po_hi_entry_image_processing_thread_queue[16 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_entry_image_processing_thread_total_fifo_size = 16;
__po_hi_local_port_t __po_hi_entry_image_processing_thread_history[16];
__po_hi_uint8_t __po_hi_entry_image_processing_thread_n_dest[__po_hi_entry_image_processing_thread_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_entry_image_processing_thread_fifo_size[__po_hi_entry_image_processing_thread_nb_ports] = {16,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_entry_image_processing_thread_destinations[__po_hi_entry_image_processing_thread_nb_ports] = {NULL,__po_hi_entry_image_processing_thread_plate_number_local_destinations};

/*!
 * \fn void entry_image_processing_thread_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task entry_image_processing_thread
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (entry_image_processing_thread_deliver) stores the incoming request for the
 *  taskentry_image_processing_thread
 */
void entry_image_processing_thread_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case entry_image_processing_thread_global_image_input:
    {
      __po_hi_gqueue_store_in (main_entry_image_processing_thread_k, entry_image_processing_thread_local_image_input, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* entry_image_processing_thread_job (void)
 * \brief Function executed by the task entry_image_processing_thread
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Get the IN ports values*/
void* entry_image_processing_thread_job (void)
{
  __po_hi_local_port_t port;
  __po_hi_request_t static image_input_request;
  parking_system__alpha_type plate_number_request_var;
  __po_hi_request_t plate_number_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (main_entry_image_processing_thread_k, __po_hi_entry_image_processing_thread_nb_ports, __po_hi_entry_image_processing_thread_queue, __po_hi_entry_image_processing_thread_fifo_size, __po_hi_entry_image_processing_thread_first, __po_hi_entry_image_processing_thread_offsets, __po_hi_entry_image_processing_thread_woffsets, __po_hi_entry_image_processing_thread_n_dest, __po_hi_entry_image_processing_thread_destinations, __po_hi_entry_image_processing_thread_used_size, __po_hi_entry_image_processing_thread_history, __po_hi_entry_image_processing_thread_recent, __po_hi_entry_image_processing_thread_empties, __po_hi_entry_image_processing_thread_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (main_entry_image_processing_thread_k, &(port));
    __po_hi_compute_next_period (main_entry_image_processing_thread_k);
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (main_entry_image_processing_thread_k, entry_image_processing_thread_local_image_input))
    {
          __po_hi_gqueue_get_value (main_entry_image_processing_thread_k, entry_image_processing_thread_local_image_input, &(image_input_request));
      __po_hi_gqueue_next_value (main_entry_image_processing_thread_k, entry_image_processing_thread_local_image_input);

    }
    /*  Call implementation*/
    parking_system__get_plate_data_from_image (image_input_request.vars.entry_image_processing_thread_global_image_input.entry_image_processing_thread_global_image_input, &(plate_number_request_var));
    /*  Set the OUT port values*/
    plate_number_request.vars.entry_image_processing_thread_global_plate_number.entry_image_processing_thread_global_plate_number = plate_number_request_var;
    plate_number_request.port = entry_image_processing_thread_global_plate_number;
    __po_hi_gqueue_store_out (main_entry_image_processing_thread_k, entry_image_processing_thread_local_plate_number, &(plate_number_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (main_entry_image_processing_thread_k, entry_image_processing_thread_global_plate_number);
  }
}

__po_hi_port_t __po_hi_exit_image_processing_thread_plate_number_local_destinations[1] = {calculate_price_global_plate_number};
__po_hi_uint8_t __po_hi_exit_image_processing_thread_woffsets[__po_hi_exit_image_processing_thread_nb_ports];
__po_hi_uint8_t __po_hi_exit_image_processing_thread_offsets[__po_hi_exit_image_processing_thread_nb_ports];
__po_hi_uint8_t __po_hi_exit_image_processing_thread_used_size[__po_hi_exit_image_processing_thread_nb_ports];
__po_hi_uint8_t __po_hi_exit_image_processing_thread_empties[__po_hi_exit_image_processing_thread_nb_ports];
__po_hi_uint8_t __po_hi_exit_image_processing_thread_first[__po_hi_exit_image_processing_thread_nb_ports];
__po_hi_request_t __po_hi_exit_image_processing_thread_recent[__po_hi_exit_image_processing_thread_nb_ports];
__po_hi_port_t __po_hi_exit_image_processing_thread_queue[16 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_exit_image_processing_thread_total_fifo_size = 16;
__po_hi_local_port_t __po_hi_exit_image_processing_thread_history[16];
__po_hi_uint8_t __po_hi_exit_image_processing_thread_n_dest[__po_hi_exit_image_processing_thread_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_exit_image_processing_thread_fifo_size[__po_hi_exit_image_processing_thread_nb_ports] = {16,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_exit_image_processing_thread_destinations[__po_hi_exit_image_processing_thread_nb_ports] = {NULL,__po_hi_exit_image_processing_thread_plate_number_local_destinations};

/*!
 * \fn void exit_image_processing_thread_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task exit_image_processing_thread
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (exit_image_processing_thread_deliver) stores the incoming request for the 
 * taskexit_image_processing_thread
 */
void exit_image_processing_thread_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case exit_image_processing_thread_global_image_input:
    {
      __po_hi_gqueue_store_in (main_exit_image_processing_thread_k, exit_image_processing_thread_local_image_input, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* exit_image_processing_thread_job (void)
 * \brief Function executed by the task exit_image_processing_thread
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Get the IN ports values*/
void* exit_image_processing_thread_job (void)
{
  __po_hi_local_port_t port;
  __po_hi_request_t static image_input_request;
  parking_system__alpha_type plate_number_request_var;
  __po_hi_request_t plate_number_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (main_exit_image_processing_thread_k, __po_hi_exit_image_processing_thread_nb_ports, __po_hi_exit_image_processing_thread_queue, __po_hi_exit_image_processing_thread_fifo_size, __po_hi_exit_image_processing_thread_first, __po_hi_exit_image_processing_thread_offsets, __po_hi_exit_image_processing_thread_woffsets, __po_hi_exit_image_processing_thread_n_dest, __po_hi_exit_image_processing_thread_destinations, __po_hi_exit_image_processing_thread_used_size, __po_hi_exit_image_processing_thread_history, __po_hi_exit_image_processing_thread_recent, __po_hi_exit_image_processing_thread_empties, __po_hi_exit_image_processing_thread_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (main_exit_image_processing_thread_k, &(port));
    __po_hi_compute_next_period (main_exit_image_processing_thread_k);
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (main_exit_image_processing_thread_k, exit_image_processing_thread_local_image_input))
    {
          __po_hi_gqueue_get_value (main_exit_image_processing_thread_k, exit_image_processing_thread_local_image_input, &(image_input_request));
      __po_hi_gqueue_next_value (main_exit_image_processing_thread_k, exit_image_processing_thread_local_image_input);

    }
    /*  Call implementation*/
    parking_system__get_plate_data_from_image (image_input_request.vars.exit_image_processing_thread_global_image_input.exit_image_processing_thread_global_image_input, &(plate_number_request_var));
    /*  Set the OUT port values*/
    plate_number_request.vars.exit_image_processing_thread_global_plate_number.exit_image_processing_thread_global_plate_number = plate_number_request_var;
    plate_number_request.port = exit_image_processing_thread_global_plate_number;
    __po_hi_gqueue_store_out (main_exit_image_processing_thread_k, exit_image_processing_thread_local_plate_number, &(plate_number_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (main_exit_image_processing_thread_k, exit_image_processing_thread_global_plate_number);
  }
}

__po_hi_port_t __po_hi_car_passed_gate_handler_thread_close_entry_gate_local_destinations[1] = {entry_gate_global_close_gate};
__po_hi_uint8_t __po_hi_car_passed_gate_handler_thread_woffsets[__po_hi_car_passed_gate_handler_thread_nb_ports];
__po_hi_uint8_t __po_hi_car_passed_gate_handler_thread_offsets[__po_hi_car_passed_gate_handler_thread_nb_ports];
__po_hi_uint8_t __po_hi_car_passed_gate_handler_thread_used_size[__po_hi_car_passed_gate_handler_thread_nb_ports];
__po_hi_uint8_t __po_hi_car_passed_gate_handler_thread_empties[__po_hi_car_passed_gate_handler_thread_nb_ports];
__po_hi_uint8_t __po_hi_car_passed_gate_handler_thread_first[__po_hi_car_passed_gate_handler_thread_nb_ports];
__po_hi_request_t __po_hi_car_passed_gate_handler_thread_recent[__po_hi_car_passed_gate_handler_thread_nb_ports];
__po_hi_port_t __po_hi_car_passed_gate_handler_thread_queue[16 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_car_passed_gate_handler_thread_total_fifo_size = 16;
__po_hi_local_port_t __po_hi_car_passed_gate_handler_thread_history[16];
__po_hi_uint8_t __po_hi_car_passed_gate_handler_thread_n_dest[__po_hi_car_passed_gate_handler_thread_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_car_passed_gate_handler_thread_fifo_size[__po_hi_car_passed_gate_handler_thread_nb_ports] = {16,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_car_passed_gate_handler_thread_destinations[__po_hi_car_passed_gate_handler_thread_nb_ports] = {NULL,__po_hi_car_passed_gate_handler_thread_close_entry_gate_local_destinations};

/*!
 * \fn void car_passed_gate_handler_thread_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task car_passed_gate_handler_thread
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (car_passed_gate_handler_thread_deliver) stores the incoming request for 
 * the taskcar_passed_gate_handler_thread
 */
void car_passed_gate_handler_thread_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case car_passed_gate_handler_thread_global_car_on_entry_gate_passing_sensor:
    {
      __po_hi_gqueue_store_in (main_car_passed_gate_handler_thread_k, car_passed_gate_handler_thread_local_car_on_entry_gate_passing_sensor, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* car_passed_gate_handler_thread_job (void)
 * \brief Function executed by the task car_passed_gate_handler_thread
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Get the IN ports values*/
void* car_passed_gate_handler_thread_job (void)
{
  __po_hi_local_port_t port;
  parking_system__alpha_type close_entry_gate_request_var;
  __po_hi_request_t close_entry_gate_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (main_car_passed_gate_handler_thread_k, __po_hi_car_passed_gate_handler_thread_nb_ports, __po_hi_car_passed_gate_handler_thread_queue, __po_hi_car_passed_gate_handler_thread_fifo_size, __po_hi_car_passed_gate_handler_thread_first, __po_hi_car_passed_gate_handler_thread_offsets, __po_hi_car_passed_gate_handler_thread_woffsets, __po_hi_car_passed_gate_handler_thread_n_dest, __po_hi_car_passed_gate_handler_thread_destinations, __po_hi_car_passed_gate_handler_thread_used_size, __po_hi_car_passed_gate_handler_thread_history, __po_hi_car_passed_gate_handler_thread_recent, __po_hi_car_passed_gate_handler_thread_empties, __po_hi_car_passed_gate_handler_thread_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (main_car_passed_gate_handler_thread_k, &(port));
    __po_hi_compute_next_period (main_car_passed_gate_handler_thread_k);
    /*  Call implementation*/
    parking_system__close_entry_gate_and_increment (&(close_entry_gate_request_var));
    /*  Set the OUT port values*/
    close_entry_gate_request.vars.car_passed_gate_handler_thread_global_close_entry_gate.car_passed_gate_handler_thread_global_close_entry_gate = close_entry_gate_request_var;
    close_entry_gate_request.port = car_passed_gate_handler_thread_global_close_entry_gate;
    __po_hi_gqueue_store_out (main_car_passed_gate_handler_thread_k, car_passed_gate_handler_thread_local_close_entry_gate, &(close_entry_gate_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (main_car_passed_gate_handler_thread_k, car_passed_gate_handler_thread_global_close_entry_gate);
  }
}

__po_hi_port_t __po_hi_calculate_price_plate_and_calculated_price_local_destinations[1] = {network_module_global_tables_and_price};
__po_hi_uint8_t __po_hi_calculate_price_woffsets[__po_hi_calculate_price_nb_ports];
__po_hi_uint8_t __po_hi_calculate_price_offsets[__po_hi_calculate_price_nb_ports];
__po_hi_uint8_t __po_hi_calculate_price_used_size[__po_hi_calculate_price_nb_ports];
__po_hi_uint8_t __po_hi_calculate_price_empties[__po_hi_calculate_price_nb_ports];
__po_hi_uint8_t __po_hi_calculate_price_first[__po_hi_calculate_price_nb_ports];
__po_hi_request_t __po_hi_calculate_price_recent[__po_hi_calculate_price_nb_ports];
__po_hi_port_t __po_hi_calculate_price_queue[16 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_calculate_price_total_fifo_size = 16;
__po_hi_local_port_t __po_hi_calculate_price_history[16];
__po_hi_uint8_t __po_hi_calculate_price_n_dest[__po_hi_calculate_price_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_calculate_price_fifo_size[__po_hi_calculate_price_nb_ports] = {16,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_calculate_price_destinations[__po_hi_calculate_price_nb_ports] = {NULL,__po_hi_calculate_price_plate_and_calculated_price_local_destinations};

/*!
 * \fn void calculate_price_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task calculate_price
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (calculate_price_deliver) stores the incoming request for the 
 * taskcalculate_price
 */
void calculate_price_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case calculate_price_global_plate_number:
    {
      __po_hi_gqueue_store_in (main_calculate_price_k, calculate_price_local_plate_number, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* calculate_price_job (void)
 * \brief Function executed by the task calculate_price
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Get the IN ports values*/
void* calculate_price_job (void)
{
  __po_hi_local_port_t port;
  __po_hi_request_t static plate_number_request;
  parking_system__alpha_type plate_and_calculated_price_request_var;
  __po_hi_request_t plate_and_calculated_price_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (main_calculate_price_k, __po_hi_calculate_price_nb_ports, __po_hi_calculate_price_queue, __po_hi_calculate_price_fifo_size, __po_hi_calculate_price_first, __po_hi_calculate_price_offsets, __po_hi_calculate_price_woffsets, __po_hi_calculate_price_n_dest, __po_hi_calculate_price_destinations, __po_hi_calculate_price_used_size, __po_hi_calculate_price_history, __po_hi_calculate_price_recent, __po_hi_calculate_price_empties, __po_hi_calculate_price_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (main_calculate_price_k, &(port));
    __po_hi_compute_next_period (main_calculate_price_k);
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (main_calculate_price_k, calculate_price_local_plate_number))
    {
          __po_hi_gqueue_get_value (main_calculate_price_k, calculate_price_local_plate_number, &(plate_number_request));
      __po_hi_gqueue_next_value (main_calculate_price_k, calculate_price_local_plate_number);

    }
    /*  Call implementation*/
    parking_system__calculate_price_for_given_plate (plate_number_request.vars.calculate_price_global_plate_number.calculate_price_global_plate_number, &(plate_and_calculated_price_request_var));
    /*  Set the OUT port values*/
    plate_and_calculated_price_request.vars.calculate_price_global_plate_and_calculated_price.calculate_price_global_plate_and_calculated_price = plate_and_calculated_price_request_var;
    plate_and_calculated_price_request.port = calculate_price_global_plate_and_calculated_price;
    __po_hi_gqueue_store_out (main_calculate_price_k, calculate_price_local_plate_and_calculated_price, &(plate_and_calculated_price_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (main_calculate_price_k, calculate_price_global_plate_and_calculated_price);
  }
}

__po_hi_port_t __po_hi_car_passed_exit_thread_close_gate_local_destinations[1] = {exit_gate_global_close_gate};
__po_hi_uint8_t __po_hi_car_passed_exit_thread_woffsets[__po_hi_car_passed_exit_thread_nb_ports];
__po_hi_uint8_t __po_hi_car_passed_exit_thread_offsets[__po_hi_car_passed_exit_thread_nb_ports];
__po_hi_uint8_t __po_hi_car_passed_exit_thread_used_size[__po_hi_car_passed_exit_thread_nb_ports];
__po_hi_uint8_t __po_hi_car_passed_exit_thread_empties[__po_hi_car_passed_exit_thread_nb_ports];
__po_hi_uint8_t __po_hi_car_passed_exit_thread_first[__po_hi_car_passed_exit_thread_nb_ports];
__po_hi_request_t __po_hi_car_passed_exit_thread_recent[__po_hi_car_passed_exit_thread_nb_ports];
__po_hi_port_t __po_hi_car_passed_exit_thread_queue[16 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_car_passed_exit_thread_total_fifo_size = 16;
__po_hi_local_port_t __po_hi_car_passed_exit_thread_history[16];
__po_hi_uint8_t __po_hi_car_passed_exit_thread_n_dest[__po_hi_car_passed_exit_thread_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_car_passed_exit_thread_fifo_size[__po_hi_car_passed_exit_thread_nb_ports] = {16,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_car_passed_exit_thread_destinations[__po_hi_car_passed_exit_thread_nb_ports] = {NULL,__po_hi_car_passed_exit_thread_close_gate_local_destinations};

/*!
 * \fn void car_passed_exit_thread_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task car_passed_exit_thread
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (car_passed_exit_thread_deliver) stores the incoming request for the 
 * taskcar_passed_exit_thread
 */
void car_passed_exit_thread_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case car_passed_exit_thread_global_car_detected:
    {
      __po_hi_gqueue_store_in (main_car_passed_exit_thread_k, car_passed_exit_thread_local_car_detected, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* car_passed_exit_thread_job (void)
 * \brief Function executed by the task car_passed_exit_thread
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Get the IN ports values*/
void* car_passed_exit_thread_job (void)
{
  __po_hi_local_port_t port;
  parking_system__alpha_type close_exit_gate_request_var;
  __po_hi_request_t close_gate_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (main_car_passed_exit_thread_k, __po_hi_car_passed_exit_thread_nb_ports, __po_hi_car_passed_exit_thread_queue, __po_hi_car_passed_exit_thread_fifo_size, __po_hi_car_passed_exit_thread_first, __po_hi_car_passed_exit_thread_offsets, __po_hi_car_passed_exit_thread_woffsets, __po_hi_car_passed_exit_thread_n_dest, __po_hi_car_passed_exit_thread_destinations, __po_hi_car_passed_exit_thread_used_size, __po_hi_car_passed_exit_thread_history, __po_hi_car_passed_exit_thread_recent, __po_hi_car_passed_exit_thread_empties, __po_hi_car_passed_exit_thread_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (main_car_passed_exit_thread_k, &(port));
    __po_hi_compute_next_period (main_car_passed_exit_thread_k);
    /*  Call implementation*/
    parking_system__close_exit_gate_and_decrement (&(close_exit_gate_request_var));
    /*  Set the OUT port values*/
    close_gate_request.vars.car_passed_exit_thread_global_close_gate.car_passed_exit_thread_global_close_gate = close_gate_request_var;
    close_gate_request.port = car_passed_exit_thread_global_close_gate;
    __po_hi_gqueue_store_out (main_car_passed_exit_thread_k, car_passed_exit_thread_local_close_gate, &(close_gate_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (main_car_passed_exit_thread_k, car_passed_exit_thread_global_close_gate);
  }
}

__po_hi_port_t __po_hi_check_slots_thread_open_gate_local_destinations[1] = {entry_gate_global_open_gate};
__po_hi_port_t __po_hi_check_slots_thread_find_another_local_destinations[1] = {network_module_global_find_antoher_parking};
__po_hi_uint8_t __po_hi_check_slots_thread_woffsets[__po_hi_check_slots_thread_nb_ports];
__po_hi_uint8_t __po_hi_check_slots_thread_offsets[__po_hi_check_slots_thread_nb_ports];
__po_hi_uint8_t __po_hi_check_slots_thread_used_size[__po_hi_check_slots_thread_nb_ports];
__po_hi_uint8_t __po_hi_check_slots_thread_empties[__po_hi_check_slots_thread_nb_ports];
__po_hi_uint8_t __po_hi_check_slots_thread_first[__po_hi_check_slots_thread_nb_ports];
__po_hi_request_t __po_hi_check_slots_thread_recent[__po_hi_check_slots_thread_nb_ports];
__po_hi_port_t __po_hi_check_slots_thread_queue[16 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_check_slots_thread_total_fifo_size = 16;
__po_hi_local_port_t __po_hi_check_slots_thread_history[16];
__po_hi_uint8_t __po_hi_check_slots_thread_n_dest[__po_hi_check_slots_thread_nb_ports] = {0,1,1};
__po_hi_int8_t __po_hi_check_slots_thread_fifo_size[__po_hi_check_slots_thread_nb_ports] = {16,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_check_slots_thread_destinations[__po_hi_check_slots_thread_nb_ports] = {NULL,__po_hi_check_slots_thread_open_gate_local_destinations,__po_hi_check_slots_thread_find_another_local_destinations};

/*!
 * \fn void check_slots_thread_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task check_slots_thread
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (check_slots_thread_deliver) stores the incoming request for the 
 * taskcheck_slots_thread
 */
void check_slots_thread_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case check_slots_thread_global_check_slots:
    {
      __po_hi_gqueue_store_in (main_check_slots_thread_k, check_slots_thread_local_check_slots, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* check_slots_thread_job (void)
 * \brief Function executed by the task check_slots_thread
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Get the IN ports values*/
void* check_slots_thread_job (void)
{
  __po_hi_local_port_t port;
  parking_system__alpha_type slot_available_request_var;
  parking_system__alpha_type slot_unavailable_request_var;
  __po_hi_request_t open_gate_request;
  __po_hi_request_t find_another_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (main_check_slots_thread_k, __po_hi_check_slots_thread_nb_ports, __po_hi_check_slots_thread_queue, __po_hi_check_slots_thread_fifo_size, __po_hi_check_slots_thread_first, __po_hi_check_slots_thread_offsets, __po_hi_check_slots_thread_woffsets, __po_hi_check_slots_thread_n_dest, __po_hi_check_slots_thread_destinations, __po_hi_check_slots_thread_used_size, __po_hi_check_slots_thread_history, __po_hi_check_slots_thread_recent, __po_hi_check_slots_thread_empties, __po_hi_check_slots_thread_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (main_check_slots_thread_k, &(port));
    __po_hi_compute_next_period (main_check_slots_thread_k);
    /*  Call implementation*/
    parking_system__check_slots_function (&(slot_available_request_var), &(slot_unavailable_request_var));
    /*  Set the OUT port values*/
    open_gate_request.vars.check_slots_thread_global_open_gate.check_slots_thread_global_open_gate = open_gate_request_var;
    open_gate_request.port = check_slots_thread_global_open_gate;
    __po_hi_gqueue_store_out (main_check_slots_thread_k, check_slots_thread_local_open_gate, &(open_gate_request));
    find_another_request.vars.check_slots_thread_global_find_another.check_slots_thread_global_find_another = find_another_request_var;
    find_another_request.port = check_slots_thread_global_find_another;
    __po_hi_gqueue_store_out (main_check_slots_thread_k, check_slots_thread_local_find_another, &(find_another_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (main_check_slots_thread_k, check_slots_thread_global_open_gate);
    error =
     __po_hi_send_output (main_check_slots_thread_k, check_slots_thread_global_find_another);
  }
}

__po_hi_port_t __po_hi_start_exit_camera_start_camera_local_destinations[1] = {exit_camera_global_start_image_acquisition};
__po_hi_uint8_t __po_hi_start_exit_camera_woffsets[__po_hi_start_exit_camera_nb_ports];
__po_hi_uint8_t __po_hi_start_exit_camera_offsets[__po_hi_start_exit_camera_nb_ports];
__po_hi_uint8_t __po_hi_start_exit_camera_used_size[__po_hi_start_exit_camera_nb_ports];
__po_hi_uint8_t __po_hi_start_exit_camera_empties[__po_hi_start_exit_camera_nb_ports];
__po_hi_uint8_t __po_hi_start_exit_camera_first[__po_hi_start_exit_camera_nb_ports];
__po_hi_request_t __po_hi_start_exit_camera_recent[__po_hi_start_exit_camera_nb_ports];
__po_hi_port_t __po_hi_start_exit_camera_queue[16 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_start_exit_camera_total_fifo_size = 16;
__po_hi_local_port_t __po_hi_start_exit_camera_history[16];
__po_hi_uint8_t __po_hi_start_exit_camera_n_dest[__po_hi_start_exit_camera_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_start_exit_camera_fifo_size[__po_hi_start_exit_camera_nb_ports] = {16,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_start_exit_camera_destinations[__po_hi_start_exit_camera_nb_ports] = {NULL,__po_hi_start_exit_camera_start_camera_local_destinations};

/*!
 * \fn void start_exit_camera_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task start_exit_camera
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (start_exit_camera_deliver) stores the incoming request for the 
 * taskstart_exit_camera
 */
void start_exit_camera_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case start_exit_camera_global_car_detected:
    {
      __po_hi_gqueue_store_in (main_start_exit_camera_k, start_exit_camera_local_car_detected, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* start_exit_camera_job (void)
 * \brief Function executed by the task start_exit_camera
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Get the IN ports values*/
void* start_exit_camera_job (void)
{
  __po_hi_local_port_t port;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (main_start_exit_camera_k, __po_hi_start_exit_camera_nb_ports, __po_hi_start_exit_camera_queue, __po_hi_start_exit_camera_fifo_size, __po_hi_start_exit_camera_first, __po_hi_start_exit_camera_offsets, __po_hi_start_exit_camera_woffsets, __po_hi_start_exit_camera_n_dest, __po_hi_start_exit_camera_destinations, __po_hi_start_exit_camera_used_size, __po_hi_start_exit_camera_history, __po_hi_start_exit_camera_recent, __po_hi_start_exit_camera_empties, __po_hi_start_exit_camera_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (main_start_exit_camera_k, &(port));
    __po_hi_compute_next_period (main_start_exit_camera_k);
    /*  Call implementation*/
    parking_system__start_camera_function ();
    /*  Set the OUT port values*/
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (main_start_exit_camera_k, start_exit_camera_global_start_camera);
  }
}

__po_hi_port_t __po_hi_start_entry_camera_start_camera_local_destinations[1] = {entry_camera_global_start_image_acquisition};
__po_hi_uint8_t __po_hi_start_entry_camera_woffsets[__po_hi_start_entry_camera_nb_ports];
__po_hi_uint8_t __po_hi_start_entry_camera_offsets[__po_hi_start_entry_camera_nb_ports];
__po_hi_uint8_t __po_hi_start_entry_camera_used_size[__po_hi_start_entry_camera_nb_ports];
__po_hi_uint8_t __po_hi_start_entry_camera_empties[__po_hi_start_entry_camera_nb_ports];
__po_hi_uint8_t __po_hi_start_entry_camera_first[__po_hi_start_entry_camera_nb_ports];
__po_hi_request_t __po_hi_start_entry_camera_recent[__po_hi_start_entry_camera_nb_ports];
__po_hi_port_t __po_hi_start_entry_camera_queue[16 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_start_entry_camera_total_fifo_size = 16;
__po_hi_local_port_t __po_hi_start_entry_camera_history[16];
__po_hi_uint8_t __po_hi_start_entry_camera_n_dest[__po_hi_start_entry_camera_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_start_entry_camera_fifo_size[__po_hi_start_entry_camera_nb_ports] = {16,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_start_entry_camera_destinations[__po_hi_start_entry_camera_nb_ports] = {NULL,__po_hi_start_entry_camera_start_camera_local_destinations};

/*!
 * \fn void start_entry_camera_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task start_entry_camera
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (start_entry_camera_deliver) stores the incoming request for the 
 * taskstart_entry_camera
 */
void start_entry_camera_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case start_entry_camera_global_car_detected:
    {
      __po_hi_gqueue_store_in (main_start_entry_camera_k, start_entry_camera_local_car_detected, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* start_entry_camera_job (void)
 * \brief Function executed by the task start_entry_camera
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Get the IN ports values*/
void* start_entry_camera_job (void)
{
  __po_hi_local_port_t port;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (main_start_entry_camera_k, __po_hi_start_entry_camera_nb_ports, __po_hi_start_entry_camera_queue, __po_hi_start_entry_camera_fifo_size, __po_hi_start_entry_camera_first, __po_hi_start_entry_camera_offsets, __po_hi_start_entry_camera_woffsets, __po_hi_start_entry_camera_n_dest, __po_hi_start_entry_camera_destinations, __po_hi_start_entry_camera_used_size, __po_hi_start_entry_camera_history, __po_hi_start_entry_camera_recent, __po_hi_start_entry_camera_empties, __po_hi_start_entry_camera_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (main_start_entry_camera_k, &(port));
    __po_hi_compute_next_period (main_start_entry_camera_k);
    /*  Call implementation*/
    parking_system__start_camera_function ();
    /*  Set the OUT port values*/
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (main_start_entry_camera_k, start_entry_camera_global_start_camera);
  }
}

__po_hi_port_t __po_hi_should_open_exit_gate_open_gate_local_destinations[1] = {exit_gate_global_open_gate};
__po_hi_uint8_t __po_hi_should_open_exit_gate_woffsets[__po_hi_should_open_exit_gate_nb_ports];
__po_hi_uint8_t __po_hi_should_open_exit_gate_offsets[__po_hi_should_open_exit_gate_nb_ports];
__po_hi_uint8_t __po_hi_should_open_exit_gate_used_size[__po_hi_should_open_exit_gate_nb_ports];
__po_hi_uint8_t __po_hi_should_open_exit_gate_empties[__po_hi_should_open_exit_gate_nb_ports];
__po_hi_uint8_t __po_hi_should_open_exit_gate_first[__po_hi_should_open_exit_gate_nb_ports];
__po_hi_request_t __po_hi_should_open_exit_gate_recent[__po_hi_should_open_exit_gate_nb_ports];
__po_hi_port_t __po_hi_should_open_exit_gate_queue[16 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_should_open_exit_gate_total_fifo_size = 16;
__po_hi_local_port_t __po_hi_should_open_exit_gate_history[16];
__po_hi_uint8_t __po_hi_should_open_exit_gate_n_dest[__po_hi_should_open_exit_gate_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_should_open_exit_gate_fifo_size[__po_hi_should_open_exit_gate_nb_ports] = {16,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_should_open_exit_gate_destinations[__po_hi_should_open_exit_gate_nb_ports] = {NULL,__po_hi_should_open_exit_gate_open_gate_local_destinations};

/*!
 * \fn void should_open_exit_gate_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task should_open_exit_gate
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (should_open_exit_gate_deliver) stores the incoming request for the 
 * taskshould_open_exit_gate
 */
void should_open_exit_gate_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case should_open_exit_gate_global_request_sent_event:
    {
      __po_hi_gqueue_store_in (main_should_open_exit_gate_k, should_open_exit_gate_local_request_sent_event, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* should_open_exit_gate_job (void)
 * \brief Function executed by the task should_open_exit_gate
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Get the IN ports values*/
void* should_open_exit_gate_job (void)
{
  __po_hi_local_port_t port;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (main_should_open_exit_gate_k, __po_hi_should_open_exit_gate_nb_ports, __po_hi_should_open_exit_gate_queue, __po_hi_should_open_exit_gate_fifo_size, __po_hi_should_open_exit_gate_first, __po_hi_should_open_exit_gate_offsets, __po_hi_should_open_exit_gate_woffsets, __po_hi_should_open_exit_gate_n_dest, __po_hi_should_open_exit_gate_destinations, __po_hi_should_open_exit_gate_used_size, __po_hi_should_open_exit_gate_history, __po_hi_should_open_exit_gate_recent, __po_hi_should_open_exit_gate_empties, __po_hi_should_open_exit_gate_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (main_should_open_exit_gate_k, &(port));
    __po_hi_compute_next_period (main_should_open_exit_gate_k);
    /*  Call implementation*/
    parking_system__open_exit_gate_function ();
    /*  Set the OUT port values*/
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (main_should_open_exit_gate_k, should_open_exit_gate_global_open_gate);
  }
}

__po_hi_port_t __po_hi_display_wallet_display_message_local_destinations[1] = {parking_display_global_display_no_money_msg};
__po_hi_uint8_t __po_hi_display_wallet_woffsets[__po_hi_display_wallet_nb_ports];
__po_hi_uint8_t __po_hi_display_wallet_offsets[__po_hi_display_wallet_nb_ports];
__po_hi_uint8_t __po_hi_display_wallet_used_size[__po_hi_display_wallet_nb_ports];
__po_hi_uint8_t __po_hi_display_wallet_empties[__po_hi_display_wallet_nb_ports];
__po_hi_uint8_t __po_hi_display_wallet_first[__po_hi_display_wallet_nb_ports];
__po_hi_request_t __po_hi_display_wallet_recent[__po_hi_display_wallet_nb_ports];
__po_hi_port_t __po_hi_display_wallet_queue[16 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_display_wallet_total_fifo_size = 16;
__po_hi_local_port_t __po_hi_display_wallet_history[16];
__po_hi_uint8_t __po_hi_display_wallet_n_dest[__po_hi_display_wallet_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_display_wallet_fifo_size[__po_hi_display_wallet_nb_ports] = {16,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_display_wallet_destinations[__po_hi_display_wallet_nb_ports] = {NULL,__po_hi_display_wallet_display_message_local_destinations};

/*!
 * \fn void display_wallet_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task display_wallet
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (display_wallet_deliver) stores the incoming request for the 
 * taskdisplay_wallet
 */
void display_wallet_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case display_wallet_global_insufficient_wallet_balance:
    {
      __po_hi_gqueue_store_in (main_display_wallet_k, display_wallet_local_insufficient_wallet_balance, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* display_wallet_job (void)
 * \brief Function executed by the task display_wallet
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Get the IN ports values*/
void* display_wallet_job (void)
{
  __po_hi_local_port_t port;
  parking_system__alpha_type message_request_var;
  __po_hi_request_t display_message_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (main_display_wallet_k, __po_hi_display_wallet_nb_ports, __po_hi_display_wallet_queue, __po_hi_display_wallet_fifo_size, __po_hi_display_wallet_first, __po_hi_display_wallet_offsets, __po_hi_display_wallet_woffsets, __po_hi_display_wallet_n_dest, __po_hi_display_wallet_destinations, __po_hi_display_wallet_used_size, __po_hi_display_wallet_history, __po_hi_display_wallet_recent, __po_hi_display_wallet_empties, __po_hi_display_wallet_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (main_display_wallet_k, &(port));
    __po_hi_compute_next_period (main_display_wallet_k);
    /*  Call implementation*/
    parking_system__display_wallet_info_function (&(message_request_var));
    /*  Set the OUT port values*/
    display_message_request.vars.display_wallet_global_display_message.display_wallet_global_display_message = display_message_request_var;
    display_message_request.port = display_wallet_global_display_message;
    __po_hi_gqueue_store_out (main_display_wallet_k, display_wallet_local_display_message, &(display_message_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (main_display_wallet_k, display_wallet_global_display_message);
  }
}


/*!
 * \fn void __po_hi_main_deliver (__po_hi_request_t* request)
 * \brief Used to deliver request to the appropriate ports
 *
 * This function takes a request as argument (\arg request) and calls the 
 * appropriate function for its delivery.To specify which function should be 
 * called, it extracts the receiver entity using the destination port.
 */
void __po_hi_main_deliver 
    (__po_hi_request_t* request)
{
  __po_hi_entity_t entity;

  entity = __po_hi_get_entity_from_global_port (request->port);
  switch (entity)
  {
    case main_display_parking_address_k_entity:
    {
      display_parking_address_deliver (request);

      break;
    }
    case main_entry_image_processing_thread_k_entity:
    {
      entry_image_processing_thread_deliver (request);

      break;
    }
    case main_exit_image_processing_thread_k_entity:
    {
      exit_image_processing_thread_deliver (request);

      break;
    }
    case main_car_passed_gate_handler_thread_k_entity:
    {
      car_passed_gate_handler_thread_deliver (request);

      break;
    }
    case main_calculate_price_k_entity:
    {
      calculate_price_deliver (request);

      break;
    }
    case main_car_passed_exit_thread_k_entity:
    {
      car_passed_exit_thread_deliver (request);

      break;
    }
    case main_check_slots_thread_k_entity:
    {
      check_slots_thread_deliver (request);

      break;
    }
    case main_start_exit_camera_k_entity:
    {
      start_exit_camera_deliver (request);

      break;
    }
    case main_start_entry_camera_k_entity:
    {
      start_entry_camera_deliver (request);

      break;
    }
    case main_should_open_exit_gate_k_entity:
    {
      should_open_exit_gate_deliver (request);

      break;
    }
    case main_display_wallet_k_entity:
    {
      display_wallet_deliver (request);

      break;
    }
    default:
    {
      break;
    }
  }
}


