#ifndef __OCARINA_GENERATED_DEPLOYMENT_H_
#define __OCARINA_GENERATED_DEPLOYMENT_H_ 
#include <po_hi_types.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

#define __PO_HI_MY_NODE main_k

#define __po_hi_display_parking_address_nb_ports 2

#define __po_hi_entry_image_processing_thread_nb_ports 2

#define __po_hi_exit_image_processing_thread_nb_ports 2

#define __po_hi_car_passed_gate_handler_thread_nb_ports 2

#define __po_hi_calculate_price_nb_ports 2

#define __po_hi_car_passed_exit_thread_nb_ports 2

#define __po_hi_check_slots_thread_nb_ports 3

#define __po_hi_start_exit_camera_nb_ports 2

#define __po_hi_start_entry_camera_nb_ports 2

#define __po_hi_should_open_exit_gate_nb_ports 2

#define __po_hi_display_wallet_nb_ports 2

/*  For each node in the distributed application add an enumerator*/

typedef enum
{
  main_k = 0
} __po_hi_node_t;

typedef enum
{
  invalid_protocol = -1
} __po_hi_protocol_t;

/*  For each thread in the distributed application nodes, add an enumerator*/

typedef enum
{
  main_display_parking_address_k_entity = 0,
  main_entry_image_processing_thread_k_entity = 1,
  main_exit_image_processing_thread_k_entity = 2,
  main_car_passed_gate_handler_thread_k_entity = 3,
  main_calculate_price_k_entity = 4,
  main_car_passed_exit_thread_k_entity = 5,
  main_check_slots_thread_k_entity = 6,
  main_start_exit_camera_k_entity = 7,
  main_start_entry_camera_k_entity = 8,
  main_should_open_exit_gate_k_entity = 9,
  main_display_wallet_k_entity = 10,
  invalid_entity = -1
} __po_hi_entity_t;

typedef enum
{
  main_display_parking_address_k = 0,
  main_entry_image_processing_thread_k = 1,
  main_exit_image_processing_thread_k = 2,
  main_car_passed_gate_handler_thread_k = 3,
  main_calculate_price_k = 4,
  main_car_passed_exit_thread_k = 5,
  main_check_slots_thread_k = 6,
  main_start_exit_camera_k = 7,
  main_start_entry_camera_k = 8,
  main_should_open_exit_gate_k = 9,
  main_display_wallet_k = 10,
  invalid_task_id = -1
} __po_hi_task_id;

typedef enum
{
  invalid_device_id = -1
} __po_hi_device_id;

typedef enum
{
  invalid_bus_id = -1,
  bus_system_bus = 0
} __po_hi_bus_id;

#define __PO_HI_NB_TASKS 11

#define __PO_HI_TASKS_STACK 0

#define __PO_HI_NB_PROTECTED 0

#define __PO_HI_NB_NODES 1

#define __PO_HI_NB_ENTITIES 11

#define __PO_HI_NB_PORTS 23

typedef enum
{
  display_parking_address_global_data_input = 0,
  display_parking_address_global_data_output = 1,
  entry_image_processing_thread_global_image_input = 2,
  entry_image_processing_thread_global_plate_number = 3,
  exit_image_processing_thread_global_image_input = 4,
  exit_image_processing_thread_global_plate_number = 5,
  car_passed_gate_handler_thread_global_car_on_entry_gate_passing_sensor = 6,
  car_passed_gate_handler_thread_global_close_entry_gate = 7,
  calculate_price_global_plate_number = 8,
  calculate_price_global_plate_and_calculated_price = 9,
  car_passed_exit_thread_global_car_detected = 10,
  car_passed_exit_thread_global_close_gate = 11,
  check_slots_thread_global_check_slots = 12,
  check_slots_thread_global_open_gate = 13,
  check_slots_thread_global_find_another = 14,
  start_exit_camera_global_car_detected = 15,
  start_exit_camera_global_start_camera = 16,
  start_entry_camera_global_car_detected = 17,
  start_entry_camera_global_start_camera = 18,
  should_open_exit_gate_global_request_sent_event = 19,
  should_open_exit_gate_global_open_gate = 20,
  display_wallet_global_insufficient_wallet_balance = 21,
  display_wallet_global_display_message = 22,
  invalid_port_t = -1,
  constant_out_identifier = 24
} __po_hi_port_t;

typedef enum
{
  display_parking_address_local_data_input = 0,
  display_parking_address_local_data_output = 1,
  entry_image_processing_thread_local_image_input = 0,
  entry_image_processing_thread_local_plate_number = 1,
  exit_image_processing_thread_local_image_input = 0,
  exit_image_processing_thread_local_plate_number = 1,
  car_passed_gate_handler_thread_local_car_on_entry_gate_passing_sensor = 0,
  car_passed_gate_handler_thread_local_close_entry_gate = 1,
  calculate_price_local_plate_number = 0,
  calculate_price_local_plate_and_calculated_price = 1,
  car_passed_exit_thread_local_car_detected = 0,
  car_passed_exit_thread_local_close_gate = 1,
  check_slots_thread_local_check_slots = 0,
  check_slots_thread_local_open_gate = 1,
  check_slots_thread_local_find_another = 2,
  start_exit_camera_local_car_detected = 0,
  start_exit_camera_local_start_camera = 1,
  start_entry_camera_local_car_detected = 0,
  start_entry_camera_local_start_camera = 1,
  should_open_exit_gate_local_request_sent_event = 0,
  should_open_exit_gate_local_open_gate = 1,
  display_wallet_local_insufficient_wallet_balance = 0,
  display_wallet_local_display_message = 1,
  invalid_local_port_t = -1
} __po_hi_local_port_t;

#define __PO_HI_NB_DEVICES 0

#define __PO_HI_NB_BUSES 1

#define __PO_HI_NB_PROTOCOLS 0

#define __PO_HI_PORT_TYPE_CONTENT __po_hi_display_parking_address_nb_ports, __po_hi_entry_image_processing_thread_nb_ports, __po_hi_exit_image_processing_thread_nb_ports, __po_hi_car_passed_gate_handler_thread_nb_ports, __po_hi_calculate_price_nb_ports, __po_hi_car_passed_exit_thread_nb_ports, __po_hi_check_slots_thread_nb_ports, __po_hi_start_exit_camera_nb_ports, __po_hi_start_entry_camera_nb_ports, __po_hi_should_open_exit_gate_nb_ports, __po_hi_display_wallet_nb_ports

#endif
