#include <activity.h>
#include <po_hi_task.h>
#include <po_hi_main.h>
#include <drivers/po_hi_driver_sockets.h>
#include <po_hi_time.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/

/*!
 * \fn __PO_HI_MAIN_TYPE __PO_HI_MAIN_NAME (void)
 * \brief Main function executed by the system
 *
 * Full function name and return types are available  in the PolyORB-HI-C 
 * runtime header files.
 */
__PO_HI_MAIN_TYPE __PO_HI_MAIN_NAME (void)
{
  
/*!
 * \var period
 * \brief Variable for task period
 *
 * This variable is used to store the valueof the period of a task when we 
 * create it. The value put in the variable is set according to AADL model 
 * description
 */
  __po_hi_time_t period;

  __po_hi_initialize_early ();
  
/*!
 * Initialize the runtime
 */
  __po_hi_initialize ();
  __po_hi_driver_sockets_init (0);
  
/*!
 * Store the period time for task display_parking_address
 */
  __po_hi_seconds (&(period), 0);
  
/*!
 * Making Sporadic task
 */
  __po_hi_create_sporadic_task (main_display_parking_address_k, &(period), 1, 0, 0, display_parking_address_job);
  
/*!
 * Store the period time for task entry_image_processing_thread
 */
  __po_hi_seconds (&(period), 0);
  
/*!
 * Making Sporadic task
 */
  __po_hi_create_sporadic_task (main_entry_image_processing_thread_k, &(period), 4, 0, 0, entry_image_processing_thread_job);
  
/*!
 * Store the period time for task exit_image_processing_thread
 */
  __po_hi_seconds (&(period), 0);
  
/*!
 * Making Sporadic task
 */
  __po_hi_create_sporadic_task (main_exit_image_processing_thread_k, &(period), 4, 0, 0, exit_image_processing_thread_job);
  
/*!
 * Store the period time for task car_passed_gate_handler_thread
 */
  __po_hi_seconds (&(period), 0);
  
/*!
 * Making Sporadic task
 */
  __po_hi_create_sporadic_task (main_car_passed_gate_handler_thread_k, &(period), 5, 0, 0, car_passed_gate_handler_thread_job);
  
/*!
 * Store the period time for task calculate_price
 */
  __po_hi_seconds (&(period), 0);
  
/*!
 * Making Sporadic task
 */
  __po_hi_create_sporadic_task (main_calculate_price_k, &(period), 2, 0, 0, calculate_price_job);
  
/*!
 * Store the period time for task car_passed_exit_thread
 */
  __po_hi_seconds (&(period), 0);
  
/*!
 * Making Sporadic task
 */
  __po_hi_create_sporadic_task (main_car_passed_exit_thread_k, &(period), 5, 0, 0, car_passed_exit_thread_job);
  
/*!
 * Store the period time for task check_slots_thread
 */
  __po_hi_seconds (&(period), 0);
  
/*!
 * Making Sporadic task
 */
  __po_hi_create_sporadic_task (main_check_slots_thread_k, &(period), 3, 0, 0, check_slots_thread_job);
  
/*!
 * Store the period time for task start_exit_camera
 */
  __po_hi_seconds (&(period), 0);
  
/*!
 * Making Sporadic task
 */
  __po_hi_create_sporadic_task (main_start_exit_camera_k, &(period), 6, 0, 0, start_exit_camera_job);
  
/*!
 * Store the period time for task start_entry_camera
 */
  __po_hi_seconds (&(period), 0);
  
/*!
 * Making Sporadic task
 */
  __po_hi_create_sporadic_task (main_start_entry_camera_k, &(period), 6, 0, 0, start_entry_camera_job);
  
/*!
 * Store the period time for task should_open_exit_gate
 */
  __po_hi_seconds (&(period), 0);
  
/*!
 * Making Sporadic task
 */
  __po_hi_create_sporadic_task (main_should_open_exit_gate_k, &(period), 3, 0, 0, should_open_exit_gate_job);
  
/*!
 * Store the period time for task display_wallet
 */
  __po_hi_seconds (&(period), 0);
  
/*!
 * Making Sporadic task
 */
  __po_hi_create_sporadic_task (main_display_wallet_k, &(period), 1, 0, 0, display_wallet_job);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  
/*!
 * Used to switch the main task to sleep all the time
 */
  __po_hi_wait_for_tasks ();
  
/*!
 * Return Statement
 */
  return (__PO_HI_MAIN_RETURN);
}


