#include <types.h>
#include <po_hi_types.h>
#include <po_hi_marshallers.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void __po_hi_marshall_type_alpha_type 
    (parking_system__alpha_type value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_int (value, message, offset);
}

void __po_hi_unmarshall_type_alpha_type 
    (parking_system__alpha_type* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_int (value, message, offset);
}

void __po_hi_marshall_request_display_parking_address_data_input 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_alpha_type (request->vars.display_parking_address_global_data_input.display_parking_address_global_data_input, message, offset);
}

void __po_hi_unmarshall_request_display_parking_address_data_input 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_alpha_type (&(request->vars.display_parking_address_global_data_input.display_parking_address_global_data_input), message, offset);
}

void __po_hi_marshall_request_display_parking_address_data_output 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_alpha_type (request->vars.display_parking_address_global_data_output.display_parking_address_global_data_output, message, offset);
}

void __po_hi_unmarshall_request_display_parking_address_data_output 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_alpha_type (&(request->vars.display_parking_address_global_data_output.display_parking_address_global_data_output), message, offset);
}

void __po_hi_marshall_request_entry_image_processing_thread_image_input 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_alpha_type (request->vars.entry_image_processing_thread_global_image_input.entry_image_processing_thread_global_image_input, message, offset);
}

void __po_hi_unmarshall_request_entry_image_processing_thread_image_input 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_alpha_type (&(request->vars.entry_image_processing_thread_global_image_input.entry_image_processing_thread_global_image_input), message, offset);
}

void __po_hi_marshall_request_entry_image_processing_thread_plate_number 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_alpha_type (request->vars.entry_image_processing_thread_global_plate_number.entry_image_processing_thread_global_plate_number, message, offset);
}

void __po_hi_unmarshall_request_entry_image_processing_thread_plate_number 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_alpha_type (&(request->vars.entry_image_processing_thread_global_plate_number.entry_image_processing_thread_global_plate_number), message, offset);
}

void __po_hi_marshall_request_exit_image_processing_thread_image_input 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_alpha_type (request->vars.exit_image_processing_thread_global_image_input.exit_image_processing_thread_global_image_input, message, offset);
}

void __po_hi_unmarshall_request_exit_image_processing_thread_image_input 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_alpha_type (&(request->vars.exit_image_processing_thread_global_image_input.exit_image_processing_thread_global_image_input), message, offset);
}

void __po_hi_marshall_request_exit_image_processing_thread_plate_number 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_alpha_type (request->vars.exit_image_processing_thread_global_plate_number.exit_image_processing_thread_global_plate_number, message, offset);
}

void __po_hi_unmarshall_request_exit_image_processing_thread_plate_number 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_alpha_type (&(request->vars.exit_image_processing_thread_global_plate_number.exit_image_processing_thread_global_plate_number), message, offset);
}

void __po_hi_marshall_request_car_passed_gate_handler_thread_close_entry_gate 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_alpha_type (request->vars.car_passed_gate_handler_thread_global_close_entry_gate.car_passed_gate_handler_thread_global_close_entry_gate, message, offset);
}

void __po_hi_unmarshall_request_car_passed_gate_handler_thread_close_entry_gate 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_alpha_type (&(request->vars.car_passed_gate_handler_thread_global_close_entry_gate.car_passed_gate_handler_thread_global_close_entry_gate), message, offset);
}

void __po_hi_marshall_request_calculate_price_plate_number 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_alpha_type (request->vars.calculate_price_global_plate_number.calculate_price_global_plate_number, message, offset);
}

void __po_hi_unmarshall_request_calculate_price_plate_number 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_alpha_type (&(request->vars.calculate_price_global_plate_number.calculate_price_global_plate_number), message, offset);
}

void __po_hi_marshall_request_calculate_price_plate_and_calculated_price 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_alpha_type (request->vars.calculate_price_global_plate_and_calculated_price.calculate_price_global_plate_and_calculated_price, message, offset);
}

void __po_hi_unmarshall_request_calculate_price_plate_and_calculated_price 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_alpha_type (&(request->vars.calculate_price_global_plate_and_calculated_price.calculate_price_global_plate_and_calculated_price), message, offset);
}

void __po_hi_marshall_request_car_passed_exit_thread_close_gate 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_alpha_type (request->vars.car_passed_exit_thread_global_close_gate.car_passed_exit_thread_global_close_gate, message, offset);
}

void __po_hi_unmarshall_request_car_passed_exit_thread_close_gate 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_alpha_type (&(request->vars.car_passed_exit_thread_global_close_gate.car_passed_exit_thread_global_close_gate), message, offset);
}

void __po_hi_marshall_request_check_slots_thread_open_gate 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_alpha_type (request->vars.check_slots_thread_global_open_gate.check_slots_thread_global_open_gate, message, offset);
}

void __po_hi_unmarshall_request_check_slots_thread_open_gate 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_alpha_type (&(request->vars.check_slots_thread_global_open_gate.check_slots_thread_global_open_gate), message, offset);
}

void __po_hi_marshall_request_check_slots_thread_find_another 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_alpha_type (request->vars.check_slots_thread_global_find_another.check_slots_thread_global_find_another, message, offset);
}

void __po_hi_unmarshall_request_check_slots_thread_find_another 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_alpha_type (&(request->vars.check_slots_thread_global_find_another.check_slots_thread_global_find_another), message, offset);
}

void __po_hi_marshall_request_display_wallet_display_message 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_alpha_type (request->vars.display_wallet_global_display_message.display_wallet_global_display_message, message, offset);
}

void __po_hi_unmarshall_request_display_wallet_display_message 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_alpha_type (&(request->vars.display_wallet_global_display_message.display_wallet_global_display_message), message, offset);
}

void __po_hi_marshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_marshall_port (request->port, message);
  switch (request->port)
  {
    case display_parking_address_global_data_input:
    {
      __po_hi_marshall_request_display_parking_address_data_input (request, message, &(offset));

      break;
    }
    case display_parking_address_global_data_output:
    {
      __po_hi_marshall_request_display_parking_address_data_output (request, message, &(offset));

      break;
    }
    case entry_image_processing_thread_global_image_input:
    {
      __po_hi_marshall_request_entry_image_processing_thread_image_input (request, message, &(offset));

      break;
    }
    case entry_image_processing_thread_global_plate_number:
    {
      __po_hi_marshall_request_entry_image_processing_thread_plate_number (request, message, &(offset));

      break;
    }
    case exit_image_processing_thread_global_image_input:
    {
      __po_hi_marshall_request_exit_image_processing_thread_image_input (request, message, &(offset));

      break;
    }
    case exit_image_processing_thread_global_plate_number:
    {
      __po_hi_marshall_request_exit_image_processing_thread_plate_number (request, message, &(offset));

      break;
    }
    case car_passed_gate_handler_thread_global_close_entry_gate:
    {
      __po_hi_marshall_request_car_passed_gate_handler_thread_close_entry_gate (request, message, &(offset));

      break;
    }
    case calculate_price_global_plate_number:
    {
      __po_hi_marshall_request_calculate_price_plate_number (request, message, &(offset));

      break;
    }
    case calculate_price_global_plate_and_calculated_price:
    {
      __po_hi_marshall_request_calculate_price_plate_and_calculated_price (request, message, &(offset));

      break;
    }
    case car_passed_exit_thread_global_close_gate:
    {
      __po_hi_marshall_request_car_passed_exit_thread_close_gate (request, message, &(offset));

      break;
    }
    case check_slots_thread_global_open_gate:
    {
      __po_hi_marshall_request_check_slots_thread_open_gate (request, message, &(offset));

      break;
    }
    case check_slots_thread_global_find_another:
    {
      __po_hi_marshall_request_check_slots_thread_find_another (request, message, &(offset));

      break;
    }
    case display_wallet_global_display_message:
    {
      __po_hi_marshall_request_display_wallet_display_message (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}

void __po_hi_unmarshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_unmarshall_port (&(request->port), message);
  switch (request->port)
  {
    case display_parking_address_global_data_input:
    {
      __po_hi_unmarshall_request_display_parking_address_data_input (request, message, &(offset));

      break;
    }
    case display_parking_address_global_data_output:
    {
      __po_hi_unmarshall_request_display_parking_address_data_output (request, message, &(offset));

      break;
    }
    case entry_image_processing_thread_global_image_input:
    {
      __po_hi_unmarshall_request_entry_image_processing_thread_image_input (request, message, &(offset));

      break;
    }
    case entry_image_processing_thread_global_plate_number:
    {
      __po_hi_unmarshall_request_entry_image_processing_thread_plate_number (request, message, &(offset));

      break;
    }
    case exit_image_processing_thread_global_image_input:
    {
      __po_hi_unmarshall_request_exit_image_processing_thread_image_input (request, message, &(offset));

      break;
    }
    case exit_image_processing_thread_global_plate_number:
    {
      __po_hi_unmarshall_request_exit_image_processing_thread_plate_number (request, message, &(offset));

      break;
    }
    case car_passed_gate_handler_thread_global_close_entry_gate:
    {
      __po_hi_unmarshall_request_car_passed_gate_handler_thread_close_entry_gate (request, message, &(offset));

      break;
    }
    case calculate_price_global_plate_number:
    {
      __po_hi_unmarshall_request_calculate_price_plate_number (request, message, &(offset));

      break;
    }
    case calculate_price_global_plate_and_calculated_price:
    {
      __po_hi_unmarshall_request_calculate_price_plate_and_calculated_price (request, message, &(offset));

      break;
    }
    case car_passed_exit_thread_global_close_gate:
    {
      __po_hi_unmarshall_request_car_passed_exit_thread_close_gate (request, message, &(offset));

      break;
    }
    case check_slots_thread_global_open_gate:
    {
      __po_hi_unmarshall_request_check_slots_thread_open_gate (request, message, &(offset));

      break;
    }
    case check_slots_thread_global_find_another:
    {
      __po_hi_unmarshall_request_check_slots_thread_find_another (request, message, &(offset));

      break;
    }
    case display_wallet_global_display_message:
    {
      __po_hi_unmarshall_request_display_wallet_display_message (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}


