#ifndef __OCARINA_GENERATED_REQUEST_H_
#define __OCARINA_GENERATED_REQUEST_H_ 
#include <types.h>
#include <po_hi_types.h>
#include <deployment.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

/*  Enumeration type for all the operations in the distributed application.*/

typedef struct
{
  __po_hi_port_t port;

  union
  {
    struct
    {
      parking_system__alpha_type display_parking_address_global_data_input;

    } display_parking_address_global_data_input;

    struct
    {
      parking_system__alpha_type display_parking_address_global_data_output;

    } display_parking_address_global_data_output;

    struct
    {
      parking_system__alpha_type entry_image_processing_thread_global_image_input;

    } entry_image_processing_thread_global_image_input;

    struct
    {
      parking_system__alpha_type entry_image_processing_thread_global_plate_number;

    } entry_image_processing_thread_global_plate_number;

    struct
    {
      parking_system__alpha_type exit_image_processing_thread_global_image_input;

    } exit_image_processing_thread_global_image_input;

    struct
    {
      parking_system__alpha_type exit_image_processing_thread_global_plate_number;

    } exit_image_processing_thread_global_plate_number;

    struct
    {
      __po_hi_bool_t car_passed_gate_handler_thread_global_car_on_entry_gate_passing_sensor;

    } car_passed_gate_handler_thread_global_car_on_entry_gate_passing_sensor;

    struct
    {
      parking_system__alpha_type car_passed_gate_handler_thread_global_close_entry_gate;

    } car_passed_gate_handler_thread_global_close_entry_gate;

    struct
    {
      parking_system__alpha_type calculate_price_global_plate_number;

    } calculate_price_global_plate_number;

    struct
    {
      parking_system__alpha_type calculate_price_global_plate_and_calculated_price;

    } calculate_price_global_plate_and_calculated_price;

    struct
    {
      __po_hi_bool_t car_passed_exit_thread_global_car_detected;

    } car_passed_exit_thread_global_car_detected;

    struct
    {
      parking_system__alpha_type car_passed_exit_thread_global_close_gate;

    } car_passed_exit_thread_global_close_gate;

    struct
    {
      __po_hi_bool_t check_slots_thread_global_check_slots;

    } check_slots_thread_global_check_slots;

    struct
    {
      parking_system__alpha_type check_slots_thread_global_open_gate;

    } check_slots_thread_global_open_gate;

    struct
    {
      parking_system__alpha_type check_slots_thread_global_find_another;

    } check_slots_thread_global_find_another;

    struct
    {
      __po_hi_bool_t start_exit_camera_global_car_detected;

    } start_exit_camera_global_car_detected;

    struct
    {
      __po_hi_bool_t start_exit_camera_global_start_camera;

    } start_exit_camera_global_start_camera;

    struct
    {
      __po_hi_bool_t start_entry_camera_global_car_detected;

    } start_entry_camera_global_car_detected;

    struct
    {
      __po_hi_bool_t start_entry_camera_global_start_camera;

    } start_entry_camera_global_start_camera;

    struct
    {
      __po_hi_bool_t should_open_exit_gate_global_request_sent_event;

    } should_open_exit_gate_global_request_sent_event;

    struct
    {
      __po_hi_bool_t should_open_exit_gate_global_open_gate;

    } should_open_exit_gate_global_open_gate;

    struct
    {
      __po_hi_bool_t display_wallet_global_insufficient_wallet_balance;

    } display_wallet_global_insufficient_wallet_balance;

    struct
    {
      parking_system__alpha_type display_wallet_global_display_message;

    } display_wallet_global_display_message;

  } vars;

} __po_hi_request_t;

#define __PO_HI_NB_OPERATIONS 0

#endif
