#include <deployment.h>
#include <po_hi_types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
const char* __po_hi_ports_names[__PO_HI_NB_PORTS] = {"display_parking_address_global_data_input","display_parking_address_global_data_output","entry_image_processing_thread_global_image_input","entry_image_processing_thread_global_plate_number","exit_image_processing_thread_global_image_input","exit_image_processing_thread_global_plate_number","car_passed_gate_handler_thread_global_car_on_entry_gate_passing_sensor","car_passed_gate_handler_thread_global_close_entry_gate","calculate_price_global_plate_number","calculate_price_global_plate_and_calculated_price","car_passed_exit_thread_global_car_detected","car_passed_exit_thread_global_close_gate","check_slots_thread_global_check_slots","check_slots_thread_global_open_gate","check_slots_thread_global_find_another","start_exit_camera_global_car_detected","start_exit_camera_global_start_camera","start_entry_camera_global_car_detected","start_entry_camera_global_start_camera","should_open_exit_gate_global_request_sent_event","should_open_exit_gate_global_open_gate","display_wallet_global_insufficient_wallet_balance","display_wallet_global_display_message"};

