#ifndef __OCARINA_GENERATED_SUBPROGRAMS_H_
#define __OCARINA_GENERATED_SUBPROGRAMS_H_ 
#include <types.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void parking_system__display_parking_address 
    (parking_system__alpha_type parking_data,
    parking_system__alpha_type* parking_address);

void parking_system__get_plate_data_from_image 
    (parking_system__alpha_type plate_image,
    parking_system__alpha_type* plate_number);

void parking_system__close_entry_gate_and_increment 
    (parking_system__alpha_type* close_entry_gate);

void parking_system__calculate_price_for_given_plate 
    (parking_system__alpha_type plate_number,
    parking_system__alpha_type* plate_and_calculated_price);

void parking_system__close_exit_gate_and_decrement 
    (parking_system__alpha_type* close_exit_gate);

void parking_system__check_slots_function 
    (parking_system__alpha_type* slot_available,
    parking_system__alpha_type* slot_unavailable);

void parking_system__start_camera_function (void);

void parking_system__open_exit_gate_function (void);

void parking_system__display_wallet_info_function 
    (parking_system__alpha_type* message);

#endif
